Initialize project structure
codescalersinternships/Flyspray pull request #13
Opened 2023-07-31 14:27 UTC by Omar622

2023-07-31 14:34 UTC, AbdelrahmanElawady commented on backend/cmd/server.go
> +	client := models.DBClient{}
change the structure so the client takes the path and App doesn't call `start` also a client doesn't need start. `NewDBClient` can open the connection

2023-07-31 15:17 UTC, rawdaGastan requested changes

2023-07-31 15:17 UTC, rawdaGastan commented on backend/app/app.go
> +	return App{client: client}
you should create a new db here and call migrate function after

2023-07-31 15:17 UTC, rawdaGastan commented on backend/models/db.go
> +type DBClient struct {
add a migrate function for the db

2023-08-01 07:40 UTC, AbdelrahmanElawady approved these changes

2023-08-01 07:44 UTC, rawdaGastan approved these changes

2023-08-01 07:47 UTC, merged