Development comment part
codescalersinternships/Flyspray pull request #18
Opened 2023-08-02 02:24 UTC by Rodina222

2023-08-02 08:14 UTC, rawdaGastan requested changes

2023-08-02 08:14 UTC, rawdaGastan commented on backend/handlers/comment.go
> +package handlers
please refer to structure issues. Handlers should be in app dir
also name it as comment_handler

2023-08-09 09:26 UTC, rawdaGastan requested changes

2023-08-09 09:26 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +type Response struct {
make sure to add the wrapper

2023-08-09 09:26 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +			ErrorResponse{Error: "bugID,ownerID and summary of the comment should be provided "})
bugID -> bug ID
ownerID -> owner ID
leave space after ,
remove the last space
errors and msgs should be user friendly as the user will deal with them, please check all

2023-08-09 09:26 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +			ErrorResponse{Error: "comment is not validated"})
you can tell that `the input data is invalid`

2023-08-09 09:26 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +	comment, err := app.client.CreateComment(comment)
I think client is misleading. db would be better

2023-08-09 09:26 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +		log.Fatal(err)
why here fatal and others are println?

2023-08-09 09:26 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +	Payload []models.Comment `json:"payload"`
payload shouldn' t be a slice of comments. needs to be more generic

2023-08-09 09:26 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +func (app *App) CreateComment(c *gin.Context) {
no need for exported handlers functions
check all

2023-08-09 09:26 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +		} else {
it should be a check `if errors.Is(err, gorm.ErrRecordNotFound)` then `if err == nil`

2023-08-09 09:26 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +	if err != nil {
it should be a check `if errors.Is(err, gorm.ErrRecordNotFound)` then `if err == nil`

2023-08-09 09:26 UTC, rawdaGastan commented on backend/models/comment.go
> +	OwnerID uint `json:"owner_id" validate:"required"`
UserID is better? no? and its string

2023-08-09 09:26 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +	if bugID == "" {
handler can have no filters

2023-08-09 09:26 UTC, rawdaGastan commented on backend/models/comment.go
> +	CreatedAt time.Time
why it doesn't have a json tag?

2023-08-09 09:26 UTC, rawdaGastan commented on backend/models/comment.go
> +func (db *DBClient) GetComment(id string) (Comment, error) {
id is uint? check all

2023-08-09 09:26 UTC, rawdaGastan commented on backend/models/comment.go
> +	if result := db.Client.First(&comment, id); result.Error != nil {
why you get it first?

2023-08-09 09:26 UTC, rawdaGastan commented on backend/models/comment.go
> +func (db *DBClient) ListComments(bugID string) []Comment {
handle if no filters

2023-08-09 09:26 UTC, rawdaGastan commented on backend/models/comment.go
> +func (db *DBClient) UpdateComment(comment Comment, id string) (Comment, error) {
you can't take the comment as is to update. Can we update IDs?

2023-08-09 09:26 UTC, rawdaGastan commented on backend/models/comment.go
> +	if result := db.Client.First(&comment, id); result.Error != nil {
why getting the comment?

2023-08-09 09:26 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +	if err := c.ShouldBindJSON(&comment); err != nil {
you should have input structs for creations and updates

2023-08-09 16:24 UTC, Rodina222 commented on backend/app/comment_handler.go
> +		log.Fatal(err)
I use fatal when the status is http.StatusInternalServerError as the server can't continue but with any other status code I use println.

2023-08-15 14:16 UTC, rawdaGastan requested changes
great work

2023-08-15 14:16 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +type CreateCommentInput struct {
no need for it to be exported

2023-08-15 14:16 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +	commentInput := CreateCommentInput{}
`var commentInput CreateCommentInput` is better

2023-08-15 14:16 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +		return nil, BadRequest(errors.New("comment ID is required"))
ID should be lowercase
check all

2023-08-15 14:16 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +	comment, err := app.DB.GetComment(uint(id))
why you used `uint`? isn't it already parsed
check all

2023-08-15 14:16 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +		return nil, InternalServerError(errors.New("failed to get comment"))
use the `internal server msg error` for all internal server errors
check all

2023-08-15 14:16 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +		return nil, NotFound(errors.New("no comments are found"))
return empty list with an Ok() response

2023-08-15 14:16 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +func (app *App) deleteComment(c *gin.Context) (interface{}, Response) {
check delete comment access (if it's not the user)

2023-08-15 14:16 UTC, rawdaGastan commented on backend/app/comment_handler.go
> +	if fmt.Sprint(userID) != fmt.Sprint(comment.UserID) {
`you have ..`

2023-08-15 14:38 UTC, rawdaGastan commented
add the issue in the pr description please
``` 
### Issues 
- you issue link
```

2023-08-15 16:35 UTC, rawdaGastan approved these changes

2023-08-15 16:36 UTC, merged