Development bug part
codescalersinternships/Flyspray pull request #25
Opened 2023-08-10 13:08 UTC by Eslam-E-Hossni

2023-08-13 11:57 UTC, rawdaGastan requested changes

2023-08-13 11:57 UTC, rawdaGastan commented on backend/app/bug_handler.go
> +	var bug models.Bug
we should have an input for the api. the model is not its input
apply for all

2023-08-13 11:57 UTC, rawdaGastan commented on backend/app/bug_handler.go
> +		return nil, BadRequest(errors.New("failed to read data"))
- log errors. zerolog is recommended
- return a friendly user errors
apply for all

2023-08-13 11:57 UTC, rawdaGastan commented on backend/app/bug_handler.go
> +		userId      = ctx.Query("user_id")
userID will not be used as a filter

2023-08-13 11:57 UTC, rawdaGastan commented on backend/app/bug_handler.go
> +	if err != nil {
we should return an empty list if no bugs found without an error

2023-08-13 11:57 UTC, rawdaGastan commented on backend/app/bug_handler.go
> +	if err != nil {
return `internal server error` as an error for the user  in case of internal server errors

2023-08-13 11:57 UTC, rawdaGastan commented on backend/app/bug_handler.go
> +	if result := app.client.Client.First(&bug, id); result.Error != nil {
use your DB's get bug function. but I think no need to get the bug before updating

2023-08-13 11:57 UTC, rawdaGastan commented on backend/app/bug_handler.go
> +	bug := models.Bug{}
add an input struct for updates. you shouldn't allow user to update all fields

2023-08-13 11:57 UTC, rawdaGastan commented on backend/app/bug_handler.go
> +		} else {
no need for else. already you used return in if condition

2023-08-13 11:57 UTC, rawdaGastan commented on backend/app/bug_handler.go
> +	id := ctx.Param("id")
why not checking on ID if it's empty?

2023-08-13 11:57 UTC, rawdaGastan commented on backend/models/bug.go
> +func (d *DBClient) UpdateBug(id string, updateBug Bug) *gorm.DB {
why taking the id and you have a bug struct? pass the ID to the struct before calling the function

2023-08-16 09:15 UTC, rawdaGastan commented
Please add your issue to the pr description. move the status of the issue to `in progress`

2023-08-20 09:27 UTC, AbdelrahmanElawady commented
Please add development updates to this branch and resolve the conflicts

2023-08-21 07:19 UTC, AbdelrahmanElawady requested changes
Looks great Eslam! Some minor comments.

2023-08-21 07:19 UTC, AbdelrahmanElawady commented on backend/app/app.go
> +	bugGroup := app.router.Group("/bug")
add authorization

2023-08-21 07:19 UTC, AbdelrahmanElawady commented on backend/app/app.go
> +		bugGroup.GET("/:id", WrapFunc(app.getSpecificBug))
`getBug` is simpler

2023-08-21 07:19 UTC, AbdelrahmanElawady commented on backend/app/bug_handler.go
> +	ComponentID int    `json:"component_id" validate:"required"`
the rest of the Bug fields should be included in user input too. Like severity, category, ..etc

2023-08-21 07:19 UTC, AbdelrahmanElawady commented on backend/app/bug_handler.go
> +	Summary string `json:"summary"`
same here

2023-08-21 07:19 UTC, AbdelrahmanElawady commented on backend/app/bug_handler.go
> +	// TODO: add middleware to check if user is signed in
this comment is not needed any more

2023-08-21 07:19 UTC, AbdelrahmanElawady commented on backend/app/bug_handler.go
> +	// TODO: add middleware to check if user is signed in
same here. not needed any more

2023-08-21 07:19 UTC, AbdelrahmanElawady commented on backend/app/bug_handler.go
> +	// TODO: add middleware to check if user is signed in
and check user it authorized

2023-08-21 07:19 UTC, AbdelrahmanElawady commented on backend/app/bug_handler.go
> +	// TODO: add middleware to check if user is signed in
remove and add user check

2023-08-21 07:19 UTC, AbdelrahmanElawady commented on backend/app/bug_handler.go
> +	}
you can update without retrieving the bug first. check RowsAffected for example

2023-08-21 07:19 UTC, AbdelrahmanElawady commented on backend/app/bug_handler.go
> +	// TODO: add middleware to check if user is signed in
remove the comment

2023-08-21 07:19 UTC, AbdelrahmanElawady commented on backend/app/bug_handler.go
> +	bug, err := app.DB.GetSpecificBug(id)
`GetBug` is enough

2023-08-21 07:19 UTC, AbdelrahmanElawady commented on backend/app/bug_handler.go
> +	if userId != bug.UserID {
the owner of the project should be able to remove bugs too, right?

2023-08-21 07:19 UTC, AbdelrahmanElawady commented on backend/app/bug_handler_test.go
> +		assert.Equal(t, http.StatusCreated, recorder.Code, "got %d status code but want status code 201", recorder.Code)
check also that bug is added to db, and for all tests check that changes are reflected in db

2023-08-21 07:19 UTC, AbdelrahmanElawady commented on backend/app/bug_handler_test.go
> +
try adding data to db and checking if filters work and return the expected data

2023-08-21 07:19 UTC, AbdelrahmanElawady commented on backend/models/bug.go
> +		Update("component_id", updatedBug.ComponentID)
you can update a lot fields in Bug struct. why only component id?

2023-08-24 10:08 UTC, rawdaGastan requested changes

2023-08-24 10:08 UTC, rawdaGastan commented on backend/app/bug_handler.go
> +	_, exists := ctx.Get("user_id")
you should check if user is allowed to get bugs
- all members in the project are allowed

2023-08-24 10:08 UTC, rawdaGastan commented on backend/app/bug_handler.go
> +		Message: "bug is retrieved successfully",
`bugs are`

2023-08-24 10:08 UTC, rawdaGastan commented on backend/app/bug_handler.go
> +	_, exists := ctx.Get("user_id")
you should check if user is allowed to get bug

2023-08-24 10:08 UTC, rawdaGastan commented on backend/app/bug_handler.go
> +		return nil, InternalServerError(errors.New("field to update bug"))
return internal server error msg

2023-08-24 10:08 UTC, rawdaGastan commented on backend/app/bug_handler.go
> +	if userId != bug.UserID && userId != project.OwnerID && !adminMember {
no need for `userId != project.OwnerID` owner is already an admin

2023-08-24 10:08 UTC, rawdaGastan commented on backend/app/bug_handler.go
> +	component, err := app.DB.GetComponent(strconv.Itoa(bug.ComponentID))
can we move access logic to a new function?

2023-08-27 12:03 UTC, rawdaGastan requested changes

2023-08-27 12:03 UTC, rawdaGastan commented on backend/models/bug.go
> +// Filterbug filters all bug by user id, bug category, bug status, component id
repeated comment?

2023-08-27 12:09 UTC, rawdaGastan approved these changes

2023-08-27 12:11 UTC, merged